---
- block:
  - name: create app config directory
    file:
      state: directory
      path: "{{ docker_src }}/{{ app_config_dir | default(default_app_config_dir) }}"
  - name: generating application config files
    template:
      src: "{{ item }}"
      dest: "{{ docker_src }}/{{ app_config_dir | default(default_app_config_dir) }}/{{ item | basename | regex_replace('\\.j2','') }}"
    with_fileglob:
        - "{{ playbook_dir }}/templates/app/*.j2"

  - name: generating default containerpilot.json
    template:
      src: "{{ item }}"
      dest: "{{ docker_src }}/etc/{{ item | basename | regex_replace('\\.j2','') }}"
    with_fileglob:
        - "{{ playbook_dir }}/create-concierge-app/templates/orchestration/containerpilot.json5.j2"
        
  - name: generate default docker-compose.yml
    template:
      src: "{{ item }}"
      dest: "{{ playbook_dir }}/{{ item | basename | regex_replace('\\.j2','') }}"
    with_fileglob:
        - "{{ playbook_dir }}/create-concierge-app/templates/orchestration/docker-compose.yml.j2"

  - name: generating custom app orchestration files
    template:
      src: "{{ item }}"
      dest: "{{ custom_orchestration_dir | default(default_custom_orchestration_dir) }}/{{ item | basename | regex_replace('\\.j2','') }}"
    with_fileglob:
        - "{{ playbook_dir }}/templates/orchestration/*.j2"
  tags:
    - configure
